menu:
  Index:
    url: /
    External: false
    name: 首页
  Tags:
    url: /tags/
    External: false
    name: 标签
#  Categories:
#    url: /categories/
#    External: false
#    name: 分类
  Equipment:
    url: /equipment/
    External: false
    name: 装备
  Projects:
    url: /projects/
    External: false
    name: 作品
  Archives:
    url: /archives/
    External: false
    name: 归档
  About:
    url: /about/
    External: false
    name: 关于

dark_theme:
  enable: true

# 联系方式
contact:
  github: "https://github.com/a-wing"
  twitter: "https://twitter.com/_a_wing"

# 是否显示封面图片
showFeatureImage: true

# 首页头像图片
#avatar: /images/avatar.png
avatar: /assets/avatar.png
# 谷歌统计 跟踪 ID
#ga: "G-2GM6102E19"

# 百度统计 The baidu web analytics
#baidu_tongji:
#
## Gittalk 评论组件
## See: https://github.com/gitalk/gitalk/
#gitalk:
#  enable: true
#  clientId: "eaa8ec37487184406145"
#  clientSecret: "77f9955d0267c1331df7cc706cfa385d2befb9c6"
#  repository: blog
#  owner: f-dong
#  createIssueManually: true
#
## 底部链接
#bottom_link:
#  icp:
#    url: https://beian.miit.gov.cn
#    text: 豫ICP备2022011962号
#    class: icp
#  gongan:
#    url: http://www.beian.gov.cn/portal/registerSystemInfo?recordcode=41010402002848
#    text: 豫公网安备41010402002848号
#    class: icp
#  rss:
#    url: # beian.miit.gov.cn
#    text: # 沪ICP备 09007032号-1
#    class: icp
#
## 底部显示来源信息
#bottom_source:
#  enable: true
#
## 脚注
#footnote:
#  enable: true # 是否开启脚注解析
#  ignoreCodeBlock: true # 是否忽略代码块中的脚注

# 图片配置
image:
  lazyload_enable: true # 图片懒加载
    #photo_zoom: simple-lightbox # 可选 simple-lightbox、fancybox、false(禁用)
  photo_zoom: fancybox # 可选 simple-lightbox、fancybox、false(禁用)

# cdn 配置
#cdn:
#  enable: false
#  # CDN 提供者
#  provider: jsdelivr # 可选 jsdelivr、unpkg、bootcdn
