# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Hi! 上天不?
description: >- # this means to ignore newlines until "baseurl:"
  新一的个人博客
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://a-wing.top" # the base hostname & protocol for your site, e.g. http://example.com

author:
  name: Metal A-wing
  email: "1 at 233 dot email"

twitter:
  username: _a_wing
  card: summary

# https://www.ietf.org/rfc/bcp/bcp47.html#section-3.2
lang: zh-CN

#image: "/assets/avatar.png"
defaults:
  - scope:
      path: ""
    values:
      image: /assets/avatar.png

# Build settings
markdown: kramdown
theme: minima

header_pages:
  - projects.md
  - equipment.md
  - links.md
  - about.md

minima:
  #skin: dark
  #skin: solarized
  #skin: solarized-dark
  social_links:
    twitter: _a_wing
    github: a-wing
    #telegram: a_wing

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-toc

google_analytics: UA-117419557-1

disqus:
  shortname: a-wing-1

show_excerpts: True
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
